name: gitpub
description: A dart repository that can provide dart code from git sources and tags as dart versions.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.16.0
  shelf: ^1.4.0
  shelf_helmet: ^2.3.0
  shelf_router: ^1.1.0
  stack_trace: ^1.12.1

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
