name: gitpub
description: A dart repository that can provide dart code from git sources and tags as dart versions.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  pub_semver: ^2.2.0
  shelf: ^1.4.0
  shelf_gzip: ^4.1.0
  shelf_helmet: ^2.3.0
  shelf_router: ^1.1.0
  stack_trace: ^1.12.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  http: ^1.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
